# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BarbrDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SideMenu'
  pod 'SwiftyStarRatingView'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SwiftLoader'
   pod 'Stripe'
  platform :ios, '8.0'
  use_frameworks!
  pod 'SDWebImage', '~>3.8'
  pod 'CVCalendar', '~> 1.4.0’
  pod 'Charts'
  
  pod 'CircleProgressView', '~> 1.0'
  
  pod 'Firebase/Core'
  pod 'SCLAlertView'  
  
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'
  
  target 'BarbrDoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BarbrDoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
